### ISSUE TITLE
Error in $: Failed reading: not a valid json value

### ISSUE THREAD

**Issue by wikiti** [tomduck/pandoc-eqnos#45] opened 2020-01-24 21:03 UTC
Hello,

First of all, nice suite of plugins.

I've tried to build the demo files (using the `Makefile`), and I keep receiving the following error, without anything built:

````
Error running filter pandoc-eqnos:
Error in $: Failed reading: not a valid json value
````

I've tried more simple files, like this one, and it still throws the same error:

````md
# SAMPLE.md

$$ y = mx + b $$ {#eq:line}

Check Equation {@eq:line}.
````

````sh
> pandoc --filter pandoc-eqnos -o sample.html SAMPLE.md
Error running filter pandoc-eqnos:
Error in $: Failed reading: not a valid json value
````

**Looks like if I build a .pdf instead of a .html file, it works.**

Here are my tool versions:

````
> pandoc --version
pandoc 2.9.1.1
Compiled with pandoc-types 1.20, texmath 0.12, skylighting 0.8.3
Default user data directory: /home/dani/.local/share/pandoc or /home/dani/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

> pandoc-eqnos --version
pandoc-eqnos 2.1.1
````

`pandoc-fignos` and `pandog-tablenos` works tho.

**Comment by fuhrmanator** [comment] 2020-01-26 18:07
I saw this error once in another filter because warnings (or status messages) were going to stdout (which must only be json). Maybe enabling full debugging (verbose) in pandoc will give some hints?

**Comment by tomduck** [comment] 2020-07-30 13:13
Thank you for your report and sorry for the long wait.  Is this still a problem for you?  I have not been able to reproduce this issue, even when I use the markdown and command you supplied.

I don't recognize your shell prompt (`>`), although perhaps you have customized it.  I tried your test under a variety of shells and it worked.

Tom

**Comment by tomduck** [comment] 2020-07-30 14:54
Note: pandoc-eqnos 2.2.0 is now released.  So, you may wish to test against that.

**Comment by tomduck** [comment] 2020-07-30 14:58
There is a similar Issue filed against pandoc-tablenos: https://github.com/tomduck/pandoc-tablenos/issues/19

**Comment by tomduck** [comment] 2020-07-30 15:43
The problem is now fixed.  Please upgrade pandoc-xnos to version 2.4.1.  Thank you for reporting this Issue.  --Tom

**Closed as completed by tomduck** 2020-07-30 15:43 UTC
