### ISSUE TITLE
eqnos-number-by-section=False is broken for (X)HTML

### ISSUE THREAD

**Issue by stroobandt** [tomduck/pandoc-eqnos#49] opened 2020-06-02 19:07 UTC
The `--metadata` customisation `eqnos-number-by-section=False`

    -M eqnos-number-by-section=False

is broken for (X)HTML. Numbering restarts with each section.

[Similar issues and possible solutions](https://github.com/tomduck/pandoc-xnos/issues/15) have been reported for `fignos-number-by-section` and `tablenos-number-by-section`.

**Comment by tomduck** [comment] 2020-07-30 12:06
Thank you for this report, and sorry for the long wait.  The problem is now fixed in the `nextrelease` branch.  Should the problem reappear after the next release, please feel welcome to re-open this issue.

Tom

**Closed as completed by tomduck** 2020-07-30 12:06 UTC
Labels: bug

**Comment by tomduck** [comment] 2020-07-30 14:55
pandoc-eqnos 2.2.0 is now released.  --Tom
