### ISSUE TITLE
Error running filter pandoc-eqnos in Windows

### ISSUE THREAD

**Issue by wyf88** [tomduck/pandoc-eqnos#6] opened 2016-01-13 05:03 UTC
When I run the following command in Windows:

```
pandoc -o test.tex --filter=pandoc-eqnos test.md
```

it says,

```
pandoc: Error running filter pandoc-eqnos
terminateProcess: permission denied (Permission denied)
```

And the same happens to pandoc-fignos and pandoc-tablenos, too. I'm using Windows 10 x64, pandoc 1.16 and Python 3.5.1. I installed the filters with pip successfully. 

```
pandoc-attributes (0.1.7)
pandoc-eqnos (0.7)       
pandoc-fignos (0.7.2)    
pandoc-tablenos (0.6)    
pandocfilters (1.3.0)    
pip (7.1.2)              
setuptools (19.2)        
```

I'm not sure what the `permission denied` means, so I also tried to change the permission of `C:\Program Files\Python` to full control for everyone, but that doesn't help. If I directly run `pandoc-eqnos`, it says `failed to create process.` 

So I'm wondering if anyone else has encountered similar problems. Thanks!

**Comment by tomduck** [comment] 2016-01-13 11:12
Thanks for your report.  It is a permissions problem, which shouldn't be too hard to sort out.  I first lneed to know a little bit more about how you installed pandoc-eqnos:
1. Did you pip install pandoc-eqnos using the "Command Prompt" or "Windows Powershell" program?  Or something else?
2. Did you perform the installation as a regular user or as the system administrator?

I will try to reproduce the error on a Windows machine I have.

**Comment by wyf88** [comment] 2016-01-13 11:20
Thanks a lot for your prompt reply! 
1. Actually I was using Cmder, a third-party console emulator for Windows, but I'm sure I was using the traditional cmd rather than Powershell inside Cmder.
2. At first I tried to use pip as a regular user, but I encountered the error of `permission denied`, so I ran cmd as administrator instead and then the installation of pandoc-eqnos was successful. But then I encountered the problem above, even after I changed the ownership and permission of the folder of Python and all its subfolders.

**Comment by tomduck** [comment] 2016-01-13 11:25
I think that I have an idea what the problem might be.  When pip installs pandoc-eqnos, there is the pandoc_eqnos.py library installed in python _and_ a pandoc-eqnos.py script (notice the dash rather than the underscore) that gets installed elsewhere.  I would guess it is the permissions for that script that are the problem.  Can you run a search for it?

**Comment by wyf88** [comment] 2016-01-13 11:41
Yes, by running `pip uninstall pandoc-eqnos`, I see

```
$ pip uninstall pandoc-eqnos
Uninstalling pandoc-eqnos-0.7:
  c:\program files\python\lib\site-packages\__pycache__\pandoc_eqnos.cpython-35.pyc
  c:\program files\python\lib\site-packages\pandoc_eqnos-0.7-py3.5.egg-info
  c:\program files\python\lib\site-packages\pandoc_eqnos.py
  c:\program files\python\scripts\pandoc-eqnos-script.py
  c:\program files\python\scripts\pandoc-eqnos.exe
Proceed (y/n)?
```

so it should be inside a subdirectory of Python. But I have changed the ownership of that directory to me and made it writable for anyone, so I don't understand where the problem comes from.

**Comment by tomduck** [comment] 2016-01-13 11:45
Can you try running the script on its own?  It should just hang rather than giving a permissions denied error.

**Comment by wyf88** [comment] 2016-01-13 11:49
Yes, when I run the script, it just hangs

```
C:\Program Files\Python\Scripts
$ python pandoc-eqnos-script.py "C:\Users\wyf88\Dropbox\BRQSEM\BRQSEM.md"
```

BTW, I'm not sure whether this is related, but when I run the .exe file, it shows

```
C:\Program Files\Python\Scripts
$ pandoc-eqnos.exe
failed to create process.

C:\Program Files\Python\Scripts
$ pandoc-fignos.exe
failed to create process.
```

**Comment by tomduck** [comment] 2016-01-13 11:54
Great, thanks.  This gives me enough to go on.  I will install under windows to see what happens.

**Comment by soloman817** [comment] 2016-03-24 08:13
I've got exactly the same issue. And I found a solution, you must install python into a path which doesn't contain space!, Try install python into "C:\Python", then it works.

**Comment by tomduck** [comment] 2016-04-03 01:53
Hi @wyf88 and @soloman817.  Sorry for the long absence.  I now have pandoc-eqnos and pandoc-fignos running under Windows 7 without a problem.  The paths for both python and pandoc-eqnos/fignos have spaces.  I don't have a Windows 8 or 10 machine, but will try to see if I can find someone to test it for me on those platforms.

**Comment by tomduck** [comment] 2016-04-03 21:27
I located a Windows 10 Surface 3 machine, and could not reproduce the error.  pandoc-eqnos is working fine for me on the two Windows systems I have access to.

When I installed python, I had to click on an option to install python's environment variables.  This is needed so that python (and pip) can be called from the command line.

**Comment by soloman817** [comment] 2016-04-04 02:17
Hi @tomduck , I guess your account name doesn't contain space! By default, Python 3.5 will be installed into `%HOME%\AppData\Program\Python\Python35-32`. And my `%HOME%` path contains space. You can try uninstall your Python and then install it into a path such as `C:\Python 35\` (Note, there is a space between "Python" and "35".

**Comment by tomduck** [comment] 2016-04-05 00:29
My mistake.  You are absolutely correct.  I have tested this under Windows 7 and 10, and can now reproduce the error under 10 but not 7.  Weird.

The error also occurs when I try to run the filter directly:

```
c:\...>"c:\Python 35-32\Scripts\pandoc-eqnos.exe"
failed to create process.
```

So, this would appear to be a problem with how the script gets installed in Windows 10.

I don't have a solution yet, but the workaround is as you recommended: Install python to a path that has no spaces.

**Comment by tomduck** [comment] 2016-04-05 01:07
AHA!  This is a problem with `pip` under Windows.  I'm using `console_scripts` in the installation process, exactly as described in [Issue #2783](https://github.com/pypa/pip/issues/2783).  It doesn't work when there is a space in python's path.

There is a better workaround than re-installing python.  You can manually download the filter and install it using `python setup.py install`.

I have also re-confirmed that this is a problem for Windows 10, but not Windows 7.  It would be lovely if someone could verify my result and test on Windows 8.

@soloman817, would you mind testing the manual install under Windows 10 to see if it works for you?  If it does, then I will make a note of the workaround in the pandoc-eqnos (and fignos/tablenos) documentation.  I will also add some new commentary to the `pip` Issue tracker.

I'm not sure at the moment what a more permanent solution is.

**Comment by tomduck** [comment] 2016-04-05 02:04
More progress. As [suggested](https://stackoverflow.com/questions/31808180/installing-pyinstaller-via-pip-leads-to-failed-to-create-process) on Stackoverflow, the problem is with an installed script that fails to have necessary quotes in the shebang line.  Specifically, for my current python installation under Windows 10, `C:\Python 35-32\Scripts\pandoc-eqnos-script.py` has the following first line:

```
 #!c:\python 35-32\python.exe
```

Changing this to 

```
 #!"c:\python 35-32\python.exe"
```

fixes the problem.

Note that there is also a `pandoc-eqnos.exe` in the `Scripts` directory.  When I compare this to my Windows 7 system, there is no `.py` script, just the `.exe`.  This is presumably why the Issue only happens in Windows 10.

I will try to find a way to remedy this problem in the install script.

**Comment by tomduck** [comment] 2016-04-05 15:16
SOLVED!  I have modified `setup.py` to fix the buggy install on Windows 10.

@soloman817 or @wyf88 , could you test it for me with the following?

```
pip install git+https://github.com/tomduck/pandoc-eqnos.git --upgrade
```

Once I have confirmation that it works for others, I will push out a new version to pypi and make similar changes to pandoc-fignos and pandoc-tablenos.

**Comment by tomduck** [comment] 2016-04-05 23:33
I decided to go ahead and post new versions to pypi for pandoc-eqnos, pandoc-fignos and pandoc-tablenos.  If it works for either of you, then please go ahead and close this issue.

**Closed as completed** 2016-04-10 01:13 UTC
Labels: bug

**Comment by spider-z3r0** [comment] 2019-10-18 23:23
I'm having a very similar issue on a mac when trying to use these filters through a sublime text build, has anyone else seen this?

**Comment by tomduck** [comment] 2019-10-27 17:21
Hi, @spider-z3r0.  This was a very windows-specific problem.  Could you please open a new Issue and provide details on what you are trying to do?  I develop and run pandoc-fignos on a mac, so we should be able to sort the problem out.

Cheers,
Tom
